image: google/cloud-sdk:alpine

production:
  stage: deploy
  environment: production
  tags:
    - ai
  only:
    - master
  script:
    - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - gcloud --quiet --project $PROJECT_ID app deploy app.yaml 

after_script:
  - rm /tmp/$CI_PIPELINE_ID.json